### ISSUE TITLE
Data files no longer exist in respository

### ISSUE THREAD

**Issue by GitOfMind** [PacktPublishing/R-Programming-By-Example#1]
The folks at Git Hub have referred me to this site in an effort to notify someone that the data files used in the book's examples no longer exist.  Git Hub tried to recover them, but with no success.  I have recently purchased the book, and I am trying learn many of the features using the examples presented.  Please upload all the data files so that readers like myself can utilize the book to its fullest.

Thank you.

**Comment by techsachinkumar** [comment]
Hi @GitOfMind 

I am able to see all the data files available in the repository.
Could you be specific about which repository your speaking about?
